name: Deploy to AWS EC2

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: almalinux-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # Your EC2 instance public IP or DNS
          username: ${{ secrets.EC2_USER }} # Your EC2 instance username
          key: ${{ secrets.EC2_SSH_KEY }} # Your private SSH key
          script: |
            echo "Deploying to EC2 instance..."
            cd /home/ec2-user/waddle-api && \
            echo "Updating code from repository..." && \
            git fetch origin main && \
            git reset --hard origin/main && \
            echo "Installing dependencies..." && \
            npm ci --omit=dev && \
            echo "Creating .env file..." && \
            touch .env && \
            echo "Setting environment variables..." && \
            echo "${{ secrets.ENV_FILE }}" >> .env && \
            npm ci --omit=dev && \
            echo "Building application..." && \
            npm run build && \
            echo "Restarting PM2 process..." && \
            pm2 restart waddleapi --update-env && \
            pm2 save && \
            echo "Deployment completed successfully!"
