name: Deploy to AWS EC2

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Store your private key in GitHub secrets

      - name: Install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Add known host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_HOST }} ssh-rsa AAAA${{ secrets.EC2_HOST_KEY }}" >> ~/.ssh/known_hosts # Adds host key, Remove StrictHostKeyChecking
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Connect using the SSH key
          ssh -o StrictHostKeyChecking=no \ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          echo "Changing to project directory..."
          cd /home/ec2-user/waddle-api && \
          echo "Updating code from repository..." && \
          git fetch origin main && \
          git reset --hard origin/main && \
          echo "Installing dependencies..." && \
          npm ci --omit=dev && \
          echo "Building application..." && \
          npm run build && \
          echo "Restarting PM2 process..." && \
          pm2 restart waddleapi --update-env && \
          pm2 save && \
          echo "Deployment completed successfully!"
        env:
          NODE_ENV: production
