name: Test and Build

on:
  push:
    branches: [main, staging]
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
          SEED_FIRST_NAME: Super
          SEED_LAST_NAME: Admin
          SEED_EMAIL: admin@waddle.uk
          SEED_PASSWORD: P@$$w0rd.
          GOOGLE_CLIENT_ID: 237136003048-3mlogbmva2mmbscg5klvuv861ktvjmen.apps.googleusercontent.com
          GOOGLE_CLIENT_SECRET: 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
          GOOGLE_CALLBACK_URL: http://localhost:3030/api/v1/auth/google/callback
          FACEBOOK_CLIENT_ID: 464940513010541
          FACEBOOK_CLIENT_SECRET: 2c9a12d4b7790dac7cb34c707b3aa2fa
          FACEBOOK_CALLBACK_URL: http://localhost:3030/api/v1/auth/facebook/redirect
          PORT: 3030
          DATABASE_URL: 'postgresql://postgres:password@localhost:5432/testdb?schema=public'
          JWT_SECRET_KEY: NkM9Ci}gVsEjwfZI07gH@CEZ}?2h
          JWT_EXPIRATION_TIME: '1h'
          JWT_REFRESH_SECRET_KEY: jwfZI07gH@CEZ}?2hNkM9Ci}gVsE
          JWT_REFRESH_EXPIRATION_TIME: '3d'
          VERIFICATION_URL: http://localhost:5173/auth/verification
          GUARDIAN_VERIFICATION_URL: http://localhost:5173/verify/guardian
          VENDOR_VERIFICATION_URL: http://localhost:5173/verify/vendor
          PASSWORD_RESET_URL: http://localhost:5173/auth/resetpassword
          SMTP_HOST: wghp1.wghservers.com
          SMTP_PORT: 465
          SMTP_USER: test@philipoyelegbin.com.ng
          SMTP_PASSWORD: NXjHG(m2FATc
          BUCKET_NAME: waddletestbucket
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

          SECRET_ACCESS_KEY: 9db13a6ed03697aa77daf530e53b5ab5df74e059e89693ea12b167a79a9e9fb5
          R2_PUBLIC_ENDPOINT: https://pub-42f91b17061547449f97974510335219.r2.dev
          S3_API: https://81c852930641402981b6a613c8239927.r2.cloudflarestorage.com
          BASE_URL: https://waddleapi.vercel.app
          FRONTEND_URL: https://waddle-admn.vercel.app
          BASE_URL_STRIPE_REFRESH: https://api.waddleapp.io/api/v1/organisers/refresh
          BASE_URL_STRIPE_RETURN: https://api.waddleapp.io/api/v1/organisers/return
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
          FRESHDESK_DOMAIN: philipoyelegbincom.freshdesk.com
          FRESHDESK_EMAIL: support@philipoyelegbincom.freshdesk.com
          FRESHDESK_API_KEY: nIV3Lubwi6Eo0qWM24Sy

          FIREBASE_TYPE: service_account
          FIREBASE_PROJECT_ID: waddle-push-notification
          FIREBASE_PRIVATE_KEY_ID: cac17d4e74c15f012a77cc53f52dd1d59cbed31e
          FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEtCve1nZeQaL7\n2Hdnwm2k3pfj97cTgGY5opjQyxROf9vQvum5J/ORzNILuSm40KKg0A4XVtAHBcUC\nHHa8D6elluolc5Du0xTiwMLhRIJLe8gV9ZQIQ//8vUGFMiLTloChtkZIg/IvH9MR\nk8C8MAXUqnlI2+7+1DheTn7MzIqkZp/cXCl52hGjeppXcSH39zR/0PaybsOoGo81\nbFRkWyNHX2K13nIJo5XrzI/XBYvLnVsnxtBeqWxJ9UBbZnJF3YZtVTEUiQWY8upA\nLChv8I+KzNK13Qpl15kBkhpUDfw+lf9PstZkaL5W29zfCGlA3toqA4Am/xzU40RN\nPE0Npk8JAgMBAAECggEAAbNG/82dx1HM7V1hJtn05axw5q0Q/Y+qEox3wrJGsikD\nxumnjoysW9HH7QcEN89B4J77yDLdaHohylNhqV1/RvyneHxnv9C+SPl+lcDoWWuv\n/pSZW3ru/wnJw7N7vpV59ivjrqPJV6PwSKIc0+OcYUq58qnIBpbiB9qo2O9ZsXMX\nwydU6+r6ci4P8rgNP3sQ6DcZI7cpfekzu32LnjEx9vAFZburpcayugXwg4qmcM0G\n1yLnbOxzntPfmIZ499cgio+7/avBbGmE3pbkEWAfY+rDj0qaurdJYsrlNuiGVdEm\nr4YNESaytdlCYGilMAwbbNA5Odaf1B2WvuKO3jpx+wKBgQDsbrG4E03zbqAQTi/l\nBxpm+wUMt8xXJkAPIeeD8URCfasu3tat9wOEmgM+tEZaHPzEt+2UHvQa0av/SLGN\nXpSRCjXGJ29JBAZ59oImpxMBt1stontO5WHVvqNYgBWIVxPnblnZ5JMmjP/6lGqw\nZ1oqPDIgEPG+LXC/muLepVsJWwKBgQDU+76+j/Dz4e08LsMsbpL33rjGIytBUWmv\n4/GsML6v7EfSV1atDNIARfZDllvI3TAAVU1YWCqQ1dTs1wZ283F09oryFhyhnjam\nA7puHqPRJAm4B8jBdSfDrXQQUir0imxmqE0yLw0DUar6KoWAgFx7F8b2xBm4swIO\n/Toiz6MSawKBgGytBOuDlBUNCG32QnWXqj8jqtKJuVdlsZRDFVPEloeplAHbU/pq\nzCcrU8qCusO5B0a09HNdNv8M2W5iT5qXmtqAQu9uOOzq+L8e2/xAV7A2Q6baRKuj\nLDE/i32mgj9FJ1T9mDdbpXfW3+KiTdf/6aX4PWIX58ZuxKCN5TJJ92p5AoGAHVEN\nv3NWyms12YviR7JsvnvE2Vkr8hC/yHtK39XR2atfc3+cKbPTEECRFlqTBcIUgmc7\nf0abjVYxuewbMrJt0pjBJXOPu1to0E9BETlceURJpjBEHQUAVToB+OEmkoSfST4v\nahH565QJQegqejaxBCyQsZTqqXbSeLe4keQc4UMCgYEAs3+huMZecJllxOnwiKBk\nrVW1x0Y/ILvRGVs8BlDPROUBWN+v9ncOJ0qpDvYWOE84mEUW+dHA56sAlrPbKdMq\nqouxJUSsLM0RL3/ozxwbVv+9SPIXirjOQudMsbCovuiHoaggODh2Kfe0FArOR/9C\nZkGxenxLGmYpBtYk7FJQMDQ=\n-----END PRIVATE KEY-----\n"
          FIREBASE_CLIENT_EMAIL: firebase-adminsdk-fbsvc@waddle-push-notification.iam.gserviceaccount.com
          FIREBASE_CLIENT_ID: 113261042783839410702
          FIREBASE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
          FIREBASE_TOKEN_URI: https://oauth2.googleapis.com/token
          FIREBASE_AUTH_PROVIDER_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
          FIREBASE_CLIENT_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40waddle-push-notification.iam.gserviceaccount.com
          FIREBASE_UNIVERSE_DOMAIN: googleapis.com

        options: >-
          --health-cmd="pg_isready" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean up dependencies
        run: rm -rf node_modules package-lock.json

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set Environment Variables
        run: |
          echo "PORT=3030" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=postgres" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV
          echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/testdb" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=NkM9Ci}gVsEjwfZI07gH@CEZ}?2h" >> $GITHUB_ENV
          echo "JWT_EXPIRATION_TIME=1h" >> $GITHUB_ENV
          echo "JWT_REFRESH_SECRET_KEY=jwfZI07gH@CEZ}?2hNkM9Ci}gVsE" >> $GITHUB_ENV
          echo "JWT_REFRESH_EXPIRATION_TIME=3d" >> $GITHUB_ENV
          echo "SEED_FIRST_NAME=Super" >> $GITHUB_ENV
          echo "SEED_LAST_NAME=Admin" >> $GITHUB_ENV
          echo "SEED_EMAIL=admin@waddle.uk" >> $GITHUB_ENV
          echo "SEED_PASSWORD=P@$$w0rd." >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=237136003048-3mlogbmva2mmbscg5klvuv861ktvjmen.apps.googleusercontent.com" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=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" >> $GITHUB_ENV
          echo "GOOGLE_CALLBACK_URL=http://localhost:3030/api/v1/auth/google/callback" >> $GITHUB_ENV
          echo "FACEBOOK_CLIENT_ID=464940513010541" >> $GITHUB_ENV
          echo "FACEBOOK_CLIENT_SECRET=2c9a12d4b7790dac7cb34c707b3aa2fa" >> $GITHUB_ENV
          echo "FACEBOOK_CALLBACK_URL=http://localhost:3030/api/v1/auth/facebook/redirect" >> $GITHUB_ENV
          echo "GUARDIAN_VERIFICATION_URL=http://localhost:5173/verify/guardian" >> $GITHUB_ENV
          echo "VENDOR_VERIFICATION_URL=http://localhost:5173/verify/vendor" >> $GITHUB_ENV
          echo "PASSWORD_RESET_URL=http://localhost:5173/auth/resetpassword" >> $GITHUB_ENV
          echo "SMTP_HOST=wghp1.wghservers.com" >> $GITHUB_ENV
          echo "SMTP_PORT=465" >> $GITHUB_ENV
          echo "SMTP_USER=test@philipoyelegbin.com.ng" >> $GITHUB_ENV
          echo "SMTP_PASSWORD=NXjHG(m2FATc" >> $GITHUB_ENV
          echo "BUCKET_NAME=waddletestbucket" >> $GITHUB_ENV
          echo "FRONTEND_URL=https://waddle-admn.vercel.app" >> $GITHUB_ENV
          echo "ACCESS_KEY_ID=6e30f43a6e34bb6db106299fc0480d7e" >> $GITHUB_ENV
          echo "AWS_REGION=eu-north-1"  >> $GITHUB_ENV
          echo "SECRET_ACCESS_KEY=9db13a6ed03697aa77daf530e53b5ab5df74e059e89693ea12b167a79a9e9fb5" >> $GITHUB_ENV
          echo "R2_PUBLIC_ENDPOINT=https://pub-42f91b17061547449f97974510335219.r2.dev" >> $GITHUB_ENV
          echo "S3_API=https://81c852930641402981b6a613c8239927.r2.cloudflarestorage.com" >> $GITHUB_ENV
          echo "BASE_URL=https://waddleapi.vercel.app" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=sk_test_51Q0lCJJ1vqI8s6tcBqAbHqYQcmompSqF3Nlh7bQ7RzVga7kHMYWlLSaz7xiFxALj5kaHXA9RLLBgM9o65NSNCbI1004n2VHSPr" >> $GITHUB_ENV
          echo "STRIPE_ENDPOINT_SECRET=whsec_533ef27f4aa69f4accf9bd07ad54ca51b0c682adf8d95931ea21b1e3e013c1d8" >> $GITHUB_ENV
          echo "FRESHDESK_DOMAIN=philipoyelegbincom.freshdesk.com" >> $GITHUB_ENV
          echo "FRESHDESK_EMAIL=support@philipoyelegbincom.freshdesk.com" >> $GITHUB_ENV
          echo "FRESHDESK_API_KEY=nIV3Lubwi6Eo0qWM24Sy" >> $GITHUB_ENV

          echo "FIREBASE_TYPE=service_account" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=waddle-push-notification" >> $GITHUB_ENV
          echo "FIREBASE_PRIVATE_KEY_ID=cac17d4e74c15f012a77cc53f52dd1d59cbed31e" >> $GITHUB_ENV
          echo "FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEtCve1nZeQaL7\n2Hdnwm2k3pfj97cTgGY5opjQyxROf9vQvum5J/ORzNILuSm40KKg0A4XVtAHBcUC\nHHa8D6elluolc5Du0xTiwMLhRIJLe8gV9ZQIQ//8vUGFMiLTloChtkZIg/IvH9MR\nk8C8MAXUqnlI2+7+1DheTn7MzIqkZp/cXCl52hGjeppXcSH39zR/0PaybsOoGo81\nbFRkWyNHX2K13nIJo5XrzI/XBYvLnVsnxtBeqWxJ9UBbZnJF3YZtVTEUiQWY8upA\nLChv8I+KzNK13Qpl15kBkhpUDfw+lf9PstZkaL5W29zfCGlA3toqA4Am/xzU40RN\nPE0Npk8JAgMBAAECggEAAbNG/82dx1HM7V1hJtn05axw5q0Q/Y+qEox3wrJGsikD\nxumnjoysW9HH7QcEN89B4J77yDLdaHohylNhqV1/RvyneHxnv9C+SPl+lcDoWWuv\n/pSZW3ru/wnJw7N7vpV59ivjrqPJV6PwSKIc0+OcYUq58qnIBpbiB9qo2O9ZsXMX\nwydU6+r6ci4P8rgNP3sQ6DcZI7cpfekzu32LnjEx9vAFZburpcayugXwg4qmcM0G\n1yLnbOxzntPfmIZ499cgio+7/avBbGmE3pbkEWAfY+rDj0qaurdJYsrlNuiGVdEm\nr4YNESaytdlCYGilMAwbbNA5Odaf1B2WvuKO3jpx+wKBgQDsbrG4E03zbqAQTi/l\nBxpm+wUMt8xXJkAPIeeD8URCfasu3tat9wOEmgM+tEZaHPzEt+2UHvQa0av/SLGN\nXpSRCjXGJ29JBAZ59oImpxMBt1stontO5WHVvqNYgBWIVxPnblnZ5JMmjP/6lGqw\nZ1oqPDIgEPG+LXC/muLepVsJWwKBgQDU+76+j/Dz4e08LsMsbpL33rjGIytBUWmv\n4/GsML6v7EfSV1atDNIARfZDllvI3TAAVU1YWCqQ1dTs1wZ283F09oryFhyhnjam\nA7puHqPRJAm4B8jBdSfDrXQQUir0imxmqE0yLw0DUar6KoWAgFx7F8b2xBm4swIO\n/Toiz6MSawKBgGytBOuDlBUNCG32QnWXqj8jqtKJuVdlsZRDFVPEloeplAHbU/pq\nzCcrU8qCusO5B0a09HNdNv8M2W5iT5qXmtqAQu9uOOzq+L8e2/xAV7A2Q6baRKuj\nLDE/i32mgj9FJ1T9mDdbpXfW3+KiTdf/6aX4PWIX58ZuxKCN5TJJ92p5AoGAHVEN\nv3NWyms12YviR7JsvnvE2Vkr8hC/yHtK39XR2atfc3+cKbPTEECRFlqTBcIUgmc7\nf0abjVYxuewbMrJt0pjBJXOPu1to0E9BETlceURJpjBEHQUAVToB+OEmkoSfST4v\nahH565QJQegqejaxBCyQsZTqqXbSeLe4keQc4UMCgYEAs3+huMZecJllxOnwiKBk\nrVW1x0Y/ILvRGVs8BlDPROUBWN+v9ncOJ0qpDvYWOE84mEUW+dHA56sAlrPbKdMq\nqouxJUSsLM0RL3/ozxwbVv+9SPIXirjOQudMsbCovuiHoaggODh2Kfe0FArOR/9C\nZkGxenxLGmYpBtYk7FJQMDQ=\n-----END PRIVATE KEY-----\n"" >> $GITHUB_ENV
          echo "FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@waddle-push-notification.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "FIREBASE_CLIENT_ID=113261042783839410702" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_URI=https://accounts.google.com/o/oauth2/auth" >> $GITHUB_ENV
          echo "FIREBASE_TOKEN_URI=https://oauth2.googleapis.com/token" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_PROVIDER_CERT_URL=https://www.googleapis.com/oauth2/v1/certs" >> $GITHUB_ENV
          echo "FIREBASE_CLIENT_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40waddle-push-notification.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "FIREBASE_UNIVERSE_DOMAIN=googleapis.com" >> $GITHUB_ENV

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h ${{ env.DB_HOST }} -p ${{ env.DB_PORT }} -U ${{ env.DB_USER }}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Create required Postgres functions
        run: |
          psql postgresql://postgres:password@localhost:5432/testdb <<'SQL'
          CREATE OR REPLACE FUNCTION generate_custom_id(prefix TEXT)
          RETURNS TEXT AS $$
          DECLARE
              random_part TEXT;
              result TEXT;
          BEGIN
              random_part := upper(substring(md5(random()::text || clock_timestamp()::text) from 1 for 5));
              result := prefix || random_part;
              RETURN result;
          END;
          $$ LANGUAGE plpgsql;

          CREATE OR REPLACE FUNCTION generate_unique_id(table_name TEXT, prefix TEXT)
          RETURNS TEXT AS $$
          DECLARE
              new_id TEXT;
              exists_check INTEGER;
          BEGIN
              LOOP
                  new_id := generate_custom_id(prefix);
                  EXECUTE format('SELECT COUNT(*) FROM "%I" WHERE id = $1', table_name)
                  USING new_id INTO exists_check;
                  IF exists_check = 0 THEN
                      EXIT;
                  END IF;
              END LOOP;
              RETURN new_id;
          END;
          $$ LANGUAGE plpgsql;
          SQL

      - name: Apply migrations
        run: npx prisma migrate deploy

      - name: Seed the database
        run: npx prisma db seed

      - name: Format Code with Prettier
        run: |
          npm run format

      - name: Lint Code with ESLint
        run: |
          npm run lint

      # - name: Run E2E Tests
      #   run: |
      #     npm run test:e2e

      - name: Build the Backend Application
        run: |
          npm run build
